"D:\Program Files\VirtualDub\vdub64.exe" /s v49.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v50.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v51.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v52.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v53.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v54.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v55.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v56.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v57.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v58.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v59.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v60.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v61.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v62.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v63.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v64.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v65.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v66.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v67.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v68.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v69.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v70.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v71.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v72.vdscript
