"D:\Program Files\VirtualDub\vdub64.exe" /s v129.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v130.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v131.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v132.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v133.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v134.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v135.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v136.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v137.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v138.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v139.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v140.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v141.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v142.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v143.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v144.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v145.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v146.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v147.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v148.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v149.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v150.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v151.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v152.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v153.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v154.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v155.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v156.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v157.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v158.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v159.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v160.vdscript
