"D:\Program Files\VirtualDub\vdub64.exe" /s v133.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v134.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v135.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v136.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v137.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v138.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v139.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v140.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v141.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v142.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v143.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v144.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v145.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v146.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v147.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v148.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v149.vdscript
