"D:\Program Files\VirtualDub\vdub64.exe" /s v217.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v218.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v219.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v220.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v221.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v222.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v223.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v224.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v225.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v226.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v227.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v228.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v229.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v230.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v231.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v232.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v233.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v234.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v235.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v236.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v237.vdscript
