rem call render-step.bat %1 v1
rem call render-step.bat %1 v2
call render-step.bat %1 v3
call render-step.bat %1 v4
call render-step.bat %1 v5
call render-step.bat %1 v6
call render-step.bat %1 v7
call render-step.bat %1 v8
call render-step.bat %1 v9
call render-step.bat %1 v10
call render-step.bat %1 v11
call render-step.bat %1 v12
call render-step.bat %1 v13
call render-step.bat %1 v14
call render-step.bat %1 v15
call render-step.bat %1 v16
call render-step.bat %1 v17
call render-step.bat %1 v18
call render-step.bat %1 v19
call render-step.bat %1 v20
call render-step.bat %1 v21
call render-step.bat %1 v22
call render-step.bat %1 v23
call render-step.bat %1 v24
call render-step.bat %1 v25
call render-step.bat %1 v26
call render-step.bat %1 v27
call render-step.bat %1 v28
call render-step.bat %1 v29
call render-step.bat %1 v30
call render-step.bat %1 v31
call render-step.bat %1 v32
