"D:\Program Files\VirtualDub\vdub64.exe" /s v169.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v170.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v171.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v172.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v173.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v174.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v175.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v176.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v177.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v178.vdscript
