"D:\Program Files\VirtualDub\vdub64.exe" /s v124.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v125.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v126.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v127.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v128.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v129.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v130.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v131.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v132.vdscript
