"D:\Program Files\VirtualDub\vdub64.exe" /s v100f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v101f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v102f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v103f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v104f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v105f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v106f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v107f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v108f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v109f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v110f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v111f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v112f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v113f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v114f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v115f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v116f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v117f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v118f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v119f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v120f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v121f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v122f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v123f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v124f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v125f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v126f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v127f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v128f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v129f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v130f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v131f.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v132f.vdscript
