"D:\Program Files\VirtualDub\vdub64.exe" /s v034.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v035.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v036.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v037.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v038.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v039.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v040.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v041.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v042.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v043.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v044.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v045.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v046.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v047.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v048.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v049.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v050.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v051.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v052.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v053.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v054.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v055.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v056.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v057.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v058.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v059.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v060.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v061.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v062.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v063.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v064.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v065.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v066.vdscript
