"D:\Program Files\VirtualDub\vdub64.exe" /s v161.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v162.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v163.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v164.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v165.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v166.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v167.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v168.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v169.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v170.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v171.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v172.vdscript
