"D:\Program Files\VirtualDub\vdub64.exe" /s v193.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v194.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v195.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v196.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v197.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v198.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v199.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v200.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v201.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v202.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v203.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v204.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v205.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v206.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v207.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v208.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v209.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v210.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v211.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v212.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v213.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v214.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v215.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v216.vdscript
