"D:\Program Files\VirtualDub\vdub64.exe" /s v097.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v098.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v099.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v100.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v101.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v102.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v103.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v104.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v105.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v106.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v107.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v108.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v109.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v110.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v111.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v112.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v113.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v114.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v115.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v116.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v117.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v118.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v119.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v120.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v121.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v122.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v123.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v124.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v125.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v126.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v127.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v128.vdscript
