"D:\Program Files\VirtualDub\vdub64.exe" /s v065.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v066.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v067.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v068.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v069.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v070.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v071.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v072.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v073.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v074.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v075.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v076.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v077.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v078.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v079.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v080.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v081.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v082.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v083.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v084.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v085.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v086.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v087.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v088.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v089.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v090.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v091.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v092.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v093.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v094.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v095.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v096.vdscript
